spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${profile}
    group:
      local:
        - common
      prod:
        - common

  datasource:
    hikari:
      maximum-pool-size: 15

---
spring:
  config:
    activate:
      on-profile: common

kopis:
  performance:
    batch-count: 200
    url: http://www.kopis.or.kr/openApi/restful
  api:
    key: ${KOPIS_API_KEY}

spotify:
  client-id: ${SPOTIFY_CLIENT_ID}
  client-secret: ${SPOTIFY_CLIENT_SECRET}

fcm:
  service-account-file: key/heyapplication-40e61-firebase-adminsdk-cd5mk-6b4dd26836.json
  project-id: heyapplication-40e61

logging:
  level:
    org.springframework.cache: DEBUG

server:
  port: 8081

management:
  endpoints:
    web:
      base-path: /health_check

---
spring.config.active.on-profile: local

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: test
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379


---
#spring.config.active.on-profile: prod
#
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/hey
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#
#  data:
#    redis:
#      host: redis
#      port: 6379
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#      format_sql: true
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#
#
#
#
